#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : psstop
Version  : 1.0
Release  : 6
URL      : https://github.com/clearlinux/psstop/archive/v1.0.tar.gz
Source0  : https://github.com/clearlinux/psstop/archive/v1.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-3.0
Requires: psstop-bin
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gthread-2.0)

%description
PPSTOP tracks the amount of memory from the process' Pss,
as shown in /proc/PID/smaps

%package bin
Summary: bin components for the psstop package.
Group: Binaries

%description bin
bin components for the psstop package.


%prep
%setup -q -n psstop-1.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1508179250
%reconfigure --disable-static
make V=1  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1508179250
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/psstop
